redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls: true

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1

applicationSet:
  replicas: 1

global:
  domain: argocd.az.cloud-people.net

certificate:
  enabled: true
